name: Fetch latest immigrant data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 20 * *"

permissions:
  contents: write

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - run: pip install -r requirements.txt

      - run: sudo env DEBIAN_FRONTEND=noninteractive apt-get update
      - run: sudo env DEBIAN_FRONTEND=noninteractive apt-get -qq -y --allow-downgrades -o 'Dpkg::Options::=--force-confold' -o=Dpkg::Use-Pty=0 install fish ghostscript

      - run: |
          for url in (lb links https://travel.state.gov/content/travel/en/legal/visa-law0/visa-statistics/immigrant-visa-statistics/monthly-immigrant-visa-issuances.html --text-include 'Issuances by FSC' --path-include .pdf)
              set date (lb dates "$url")
              set file "immigrant_data/$date.jsonl"

              if not test -e "$file"
                  echo "Saving $file"
                  echo "$url"
                  lb markdown-tables "$url" --start-row 1 --concat --to-json > "$file"
              end
          end
        shell: fish {0}

      - name: Commit and push if changed
        run: |
          git config --local user.email "actions@users.noreply.github.com"
          git config --local user.name "GitHub Action"
          git add -A
          timestemp=$(date -u)
          git commit -m "Latest data: ${timestemp}" || exit 0
          git pull
          git push
